### ISSUE TITLE
No context menu when using Eclipse

### ISSUE THREAD

**Issue by StefanLecho** [ContextMapper/contextmapper.github.io#86] opened 2023-04-27 11:49 UTC
In Eclipse I've created a General and a Java Project and added to both a new .cml file.
When adding this file, Eclipse does not ask to convert the project to XText and I neither see the context menu's.
Even when I manually convert the project to XText.

How can this be corrected ?

-Eclipse Version 2023-03 (4.27.0)
-Context Map Generator 1.2.1
-Context Mapper DSL Editor 6.7.0
-Context Mapper DSL Editor Developer Resources 6.7.0

**Comment by stefan-ka** [comment] 2023-04-28 06:19
Hi @StefanLecho 

I also tested with Eclipse 2023-03 now and unfortunately I cannot reproduce the problem. Works fine for me...

Which Eclipse package do you use? (https://www.eclipse.org/downloads/packages/)
Which Java version have you installed?
How have you installed Context Mapper? Via Marketplace or manually via URL?

Best regards,
Stefan

**Comment by stefan-ka** [comment] 2023-06-09 07:48
@StefanLecho 

Maybe try with Eclipse 2022-12? Just saw now that with Eclipse 2023-03 there are some issues. Interesting that it worked for me in April.

**Comment by stefan-ka** [comment] 2024-01-04 12:56
@StefanLecho 

Since we couldn't reproduce your issue, I'll close this one. Please let me know if you still have troubles.

Best regards,
Stefan

**Closed by stefan-ka** 2024-01-04 12:56 UTC

**Comment by StefanLecho** [comment] 2024-01-06 11:05
I confirm that it works with Eclipse 2022-12.
